# -*- coding: utf-8 -*-
"""type of prints.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ysc4WWwPT383foajeKjxzRL9YuzqGY8I
"""

# Using multiple quotation marks
print('"안녕하세요"라고 말했습니다')

# Line break
print("""\
동해물과\
""")

# Various escape characters (\ = backslash)
# \n: newline
# \t: tab
# \\: represents a backslash
print("서정빈\t나이\t지역")

# String concatenation operator
print("안녕" + "하셈")
print("hello" + "!")

# String repetition operator
print("hello"*3)
print(3*"hello")

# Character selection operator (indexing: [])
print("문자 선택 연산자에 대해 알아볼까요?")
print("안녕하세요"[0])
print("안녕하세요"[1])
print("안녕하세요"[2])
print("안녕하세요"[3])
print("안녕하세요"[4])
print("")

print("안녕하세요"[-1])
print("안녕하세요"[-2])
print("안녕하세요"[-3])
print("안녕하세요"[-4])
print("안녕하세요"[-5])

# String slicing operator: [:]
print("안녕하세요"[1:4])
# Python does not include the last index

# Other slicing examples
print("안녕하세요"[:3])
print("안녕하세요"[1:])

# Getting the length of a string with len()
print(len("안녕하쇼"))

"""# 새 섹션"""